### ISSUE TITLE
App fails to run and build

### ISSUE THREAD

**Issue by drexhacker** [Kommunicate-io/Kommunicate-Flutter-Plugin#43] opened 2021-09-04 14:59 UTC
The plugin `kommunicate_flutter` uses a deprecated version of the Android embedding.

**Comment by Kommunicate-chat** [comment] 2021-09-06 16:17
-- Please reply above this line --


            Hello 

Thanks for notifying the issue, Our tech team will check and update
the solution.
***@***.***
How would you rate my reply?
Great [1]    Okay [2]    Not Good [3]

--
Kommunicate KM
***@***.***


Links:
------
[1]
https://secure.helpscout.net/satisfaction/453861400/record/4730878725/1/
[2]
https://secure.helpscout.net/satisfaction/453861400/record/4730878725/2/
[3]
https://secure.helpscout.net/satisfaction/453861400/record/4730878725/3/

**Comment by amntoppo** [comment] 2021-09-08 07:49
It shows a warning message, but we are able to build and run the code. Can you check if this or a different issue is preventing the build?

This will be fixed in the next release.

**Closed** 2021-10-01 06:03 UTC
Labels: released

**Comment by chaturadilan** [comment] 2021-12-04 02:42
even in version 1.3.2 the issue is there. However, it does not break the build but shows an unpleasant warning message when running and pub get
